In [1]:
import numpy as np

In [58]:
x=np.array([5000,20000,30000,50000,35000,60000,24000,55000,28000,52000]).reshape(-1,1)

In [59]:
y=np.array(['NO','NO','NO','YES','NO','YES','NO','YES','NO','YES'])

In [60]:
x

array([[ 5000],
       [20000],
       [30000],
       [50000],
       [35000],
       [60000],
       [24000],
       [55000],
       [28000],
       [52000]])

In [61]:
y

array(['NO', 'NO', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES'],
      dtype='<U3')

In [14]:
from sklearn import preprocessing

In [48]:
le=preprocessing.LabelEncoder()

In [64]:
y_new=le.fit_transform(y)

In [65]:
y_new

array([0, 0, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int64)

In [37]:
from sklearn.linear_model import LogisticRegression

In [38]:
model=LogisticRegression()

In [66]:
model.fit(x,y_new)

LogisticRegression()

In [67]:
y_pred=model.predict(x)

In [75]:
x_eval=np.array([45000,51000]).reshape(-1,1)
y_eval=model.predict(x_eval)
y_eval

array([1, 1], dtype=int64)

#### y_pred

In [69]:
from sklearn import metrics

In [70]:
metrics.confusion_matrix(y,y_pred)

array([[6, 0],
       [0, 4]], dtype=int64)

In [84]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x, y_new, test_size = .25)

In [85]:
model.fit(X_train,Y_train)

LogisticRegression()

In [86]:
model.predict(X_test)

array([0, 0, 1], dtype=int64)

In [88]:
X_test

array([[24000],
       [35000],
       [60000]])

In [89]:
X_train

array([[55000],
       [50000],
       [20000],
       [28000],
       [30000],
       [ 5000],
       [52000]])

In [81]:
Y_test

array([1, 0, 1, 0, 1, 0, 0, 0], dtype=int64)

In [92]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()



In [94]:
classifier.fit(X_train,Y_train)

KNeighborsClassifier()

In [98]:
predictions=classifier.predict(X_test)

In [96]:
X_test

array([[24000],
       [35000],
       [60000]])

In [99]:
predictions

array([0, 0, 1], dtype=int64)

In [100]:
metrics.confusion_matrix(Y_test,predictions)

array([[2, 0],
       [0, 1]], dtype=int64)

In [102]:
metrics.accuracy_score(Y_test,predictions)

1.0