In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
x=np.array([5,15,25,35,45,55]).reshape((-1,1))
y=np.array([10,30,50,70,90,110])

In [3]:
x


array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [29]:
y

array([ 10,  30,  50,  70,  90, 110])

In [30]:
model=LinearRegression()

In [31]:
model.fit(x,y)

LinearRegression()

In [32]:
r_sq=model.score(x,y)
r_sq

1.0

In [33]:
print('intercept:',model.intercept_)

intercept: 0.0


In [34]:
print('slope:',model.coef_)

slope: [2.]


In [35]:
y_pred=model.predict(x)
print('predicted response:',y_pred,sep='\n')

predicted response:
[ 10.  30.  50.  70.  90. 110.]
